* Chapter 1
** Section 1
*** Misc questions	 
   - Remark in proposition 1.10, why is the chain of closures maximal?
	 Suppose $\exists i$ such that $\overline{Z_0} \subseteq \cdots  \subseteq Z_{\overline{i+1}} \subseteq \overline{Z_{i+1}} \subseteq \cdots \subseteq \overline{Z_n}$
	 
	 $Z_{\overline{i+1}}$ is closed in $Y$, we will show it's irreducible later. Therefore, $\overline{Z_i} = Z_{i+1}\cap Y$ or $\overline{Z_{i+1}} = Z_{\overline{i+1}}\cap Y$. However, the latter would contradict the definition of closure for $Z_{i+1}$ because $Z_{\overline{i+1}}\subset \overline{Z_i}$ yet $Z_{\overline{i+1}}$ contains $Z_i$

	 So $\overline{Z_i} = Z_{\overline{i+1}}\cap Y$. But then $(Z_{\overline{i+1}}\backslash\overline{Z_i})\cap Y = \emptyset$ for if it didn't, then $Z_{\overline{i+1}}\cap Y$ would contain elements not in $Z_i$. Therefore, $Z_{\overline{i+1}}$ consists of elements specifically in the closure of $Y$ and the elements of $\overline{Z_i}$ so $Z_{\overline{i+1}} = )(\overline{Y}\backslash Y)\cap Z_{\overline{i+1}}) \cup\overline{Z_i}$ each of the two components in the union is a closed subset of $Z_{\overline{i+1}}$, a contradiction.

   - Do the algebraic manipulations that corresponds to intersecting two varieties have any "intrinsic" geometric interpretation?

	 To illustrate, here's an example I worked out for exercise 1.8: consider intersecting the line $x = y = z$ with the unit sphere defined by $x^2 + y^2 + z^2 - 1$. The ideal for the intersection is $(x^2 + y^2 + z^2 - 1, x - y, y - z)$. Now, let's perform some algebraic manipulations:
	 4. $(3y^2 - 1, x - y, y -z)$ Because by the relations, we assume $y = x = z$
	 5. $((y + \frac{1}{\sqrt{3}})(y - \frac{1}{\sqrt{3}}), x - y, y - z)$ factoring $3y^2 - 1$
	 6. $Z(y - \frac{1}{\sqrt{3}}, x - y, y - z)\cup Z(y + \frac{1}{\sqrt{3}}, x - y, y - z)$
	 7. $Z(y - \frac{1}{\sqrt{3}}, x - \frac{1}{\sqrt{3}}, z - \frac{1}{\sqrt{3}})\cup Z(y + \frac{1}{\sqrt{3}}, x - \frac{1}{\sqrt{3}}, z - \frac{1}{\sqrt{3}})$

	 Interestingly, even though we get the two points at which the unit sphere intersects the line, $x = y = z$, "breaking down" $x^2 + y^2 + z^2 - 1$ in this way gives us two hyperplanes defined by $y + \frac{1}{\sqrt{3}}$ and $y - \frac{1}{\sqrt{3}}$ respectively. These hyperplanes are not subvarieties of the sphere, but they do intersect the sphere at the subvariety (point) at which the line $x = y = z$ intersects the sphere. 
		
	 I'm not convinced that there's anything particularly interesting "happening to" the added variety and I think it might be more straightforward to think about it in terms of algebra:
	 Consider the case adding a new generator to an ideal $(f_1,\cdots,f_r) = I\subset k[x_1,\cdots,x_n]$ yielding a new ideal $(f_1,\cdots,f_r,f_{r+1}) = J$. This means that, in order for a point $p\in k^n$ to be an element of $Z(J)$, all of the generators $I$ must evaluate to zero at $p$, and also $f_{r+1}$. However, there may be elements of the new generator introduced by $J$ that are redundant in terms of all of the relations in $I$ (i.e., some subcomponents must already be zero due to a generator, some subexpressions might be equivalent, etc.,). Reducing the new generator (or perhaps generators originally from $I$ given the introduction of $f_{r+1}$), is the process of removing those "redundant" subexpressions of generators that are needed to specify a point in $Z(J)$.

	 One could give the geometric interpretation of "any points of $Z(J)$ that intersect $Z(I)$ satisfy whatever $f_{r+1}$ reduces to as part of $J$, so let's just introduce that hypersurface instead of $f_{r+1}$", but I find it very unsatisfying to think of it in that way.

*** Exercises
**** 1.1a
	 Let $Y = y - x^2$ Define $\varphi: k[x,y]\slash (y-x^2)\to k[z]$ to be $\varphi(ax + by + c) = az + bz^2 + c$. This is clearly surjective as any element $a_nz^n + \cdots + a_0$ has in its preimage $a_nx^n + \cdots + a_0$. Now to show its injective: Suppose there was some non-zero polynomial $p(x,y)\in k[x,y]\slash (y-x^2)$ such that $\varphi(p(x,y)) = 0$ then the process of replacing all of the instances of $y$ with $x^2$ renders the polynomial to be zero. However, the relation defined on $k[x,y]\slash (y-x^2)$ declares that $y \cong x^2$ which means that $p(x,y)$ was zero to begin with.

**** 1.1b
	 Let $A = k[x,y]\slash(xy - 1)$. Suppose $\exists\varphi: A\to k[x]$. Then, if this were to be an isomorphism, $1 = \varphi(1) = \varphi(xy) = \varphi(x)\varphi(y)$. However, the only units of $k[x]$ are the elements of $k$. If $x,y$ were to map to say, $f,f^{-1}\in k$ respectively, then $f$ or $f^{-1}$ needs to map to, say, $x$ in order for surjectivity to hold (we could have also chosen $y$, but that has no influence on the proof). However, $x$ has no inverse and therefore $1 = \varphi(ff^{-1}) = \varphi(f)\varphi(f^{-1}) = x\varphi(f^{-1})\ne 1$ a contradiction.

**** 1.1c
	 Skipped for now

**** 1.2
	 Let $A = k[x,y,z]\backslash(x^2-y, x^3-z)$ and define $\varphi: A\to k[w]$ to be $\varphi(x)\to w, \varphi(y) = w^2, \varphi(z) = w^3$. By an argument similar to $1.1a$, this is clearly surjective and to show it's injective, let $\varphi(p(x,y,z)) = 0$ with $p(x,y,z)\ne 0$. Then this means that replacing $x$ with $w$, $y$ with $w^2$, and $z$ with $w^3$ makes $p(x,y,z)$ become zero. However, these are the same relations in $A$.

**** 1.3
	 Lemma: $Z(a + b) = Z(a)\cap Z(b)$.
	 By prop 1.2.a, $Z(a)\supseteq Z(a + b)$ and also $Z(b)\supset Z(a+b)$ so every element of $Z(a+b)$ is an element of both $Z(a)$ and $Z(b)$ so $Z(a+b)\subseteq Z(a)\cap Z(b)$. Now, take an element of $Z(a)\cap Z(b)$ call it $z$. $\forall i\in a$, $i(z) = 0$. Similarly, $\forall j\in b$, $j(z) = 0$ so $(i + j)(z) = 0$ so $Z(a)\cap Z(b) \supseteq Z(a+b)$

	 Therefore $Z(x^2 - yz, xz - x) = Z(x^2 - yz)\cap Z(xz - x) = Z(x^2 - yz)\cap (Z(x)\cup Z(z -1)) = (Z(x^2 - yz)\cap Z(x))\cup(Z(x^2 - yz)\cap Z(z-1))$. Notably, $Z(x^2 - yz)$ intersects $Z(x)$ precisely where $x = 0$ and with $Z(z-1)$ where $z = 1$ so the first component reduces to $Z(-yz) = Z(y)\cup Z(z)$ and the second component reduces to $Z(x^2 - y)$. Putting it all together, $Z(y)\cup Z(z)\cup Z(x^2-y)$


**** 1.4
	 The prime ideal $x$ corresponds to the infinite set of the points where $x = 0$. $A^2$ only has finit sets as closed sets.

**** 1.5
	 $\Rightarrow$ The affine coordinate ring of $Y$ is of the form $A = k[x_1,\cdots,x_n]\slash I(Z(T)) = k[x_1,\cdots,x_n]\slash\sqrt{(T)}$ for some $T\subset k[x_1,\cdots,x_n]$ which has nilradical 0 by the definition of the radical. Because $A$ is noetherian $\sqrt{(T)}$ is finitely generated and, because $k[x_1,\cdots,x_n]$ is finitely generate, $A$ is finitely generated as well. Therefore $A$ is a finitely generate $k$ algebra with no nilpotent elements. So if $B$ is isomorphic to $A$, it must also be a finitely generated $k$ algebra with no nilpotent elements.

	 $\Leftarrow$ Enumerate the generators of $B$ as $x_1,\cdots, x_n$ which we may do because $B$ is finitely generated and let $R$ be the set of relations. Let us define $\varphi: B\to k[x_1,\cdots,x_n]\slash R$ where $x_i \mapsto x_i$ Similarly to 1.1a and 1.2, this is surjective and, because the relations of the two rings are the same, it's injective as well. It only remains to show that $R$ is of the form $I(Z(T))$ or, in other words, radical. However, this is equivalent to saying that the nilradical of $B$ is zero, which is one of our assumptions.

**** 1.6
	 Let $Y\subseteq X$ be open. If $Y = Y_1\cup Y_2$ in the induced topology, then $X = (X\backslash Y)\cup Y_1\cup Y_2$, each of which is a closed, proper subset of $X$.

	 Similarly, let $Y\subseteq X$ be open. If $\overline{Y} = Y_1\cup Y_2$ then $X = \overline{Y}\cup (X\backslash Y)$.

	 Let $Y\subseteq X$ be irreducible. If $\overline{Y} = Y_1\cup Y_2$, then $(Y\cap Y_1)\cup(Y\cap Y_2) = Y$ then $Y\cap Y_1 = Y$ or $Y\cap Y_2 = Y$ but that would contradict that $\overline{Y}$ is the smallest closed set containing $Y$.

**** 1.7a
	 Note: We take "family of x sets" (e.g., a family of closed sets) to mean a set whose elements are in turn x sets (e.g., closed). This is consistent with his use of the term "family" in proposition 1.1 (that algebraic sets form a topology)
	 - $X$ Noetherian $\Rightarrow$ family of closed sets has a minimal element.
	   Let $Y$ be a family of closed sets. Consider an element $Y_1\in Y$. If there is no other element $Y_2\in Y$ such that $Y_1\supset Y_2$, then $Y_1$ is minimal. Otherwise, we have the start of a chain $Y_1\supset Y_2$; because $X$ is noetherian, we can iteratively continue this process of finding closed sets $Y_{i+1}$ that are subsets of $Y_i$ and that we'll eventually stabilize for some integer $n$ (which is to say, $\forall N > n, Y_N = Y_n$) so $Y_n$ is a minimal element.
	 - Family of closed sets has a minimal element $\Rightarrow X$ noetherian
	   Let $\tilde{X} = X_0\supseteq X_1\supseteq X_2\supseteq\cdots$ be a (possibly infinite) sequence of closed subsets. By assumption, $\tilde{X}$ has a minimal element, call it $X_i$. Because $\tilde{X}$ may be infinite, this means that $\forall I > i, X_I = X_i$ because, by the construction of $\tilde{X}$, $j > i\Rightarrow X_i\supseteq X_j$.
	 - $X$ satisfies a.c.c. on open sets $\Rightarrow X$ noetherian
	   Let $X_1\supseteq X_2\supseteq\cdots$ be an arbitrary chain of closed subsets of $X$. Then $(X\backslash X_1)\subseteq (X\backslash X_2)\subseteq\cdots$ is a chain of open sets. By assumption, the chain of open sets has some set $X\backslash X_i$ such that, $\forall I > i, (X\backslash X_I) = (X\backslash X_i)$. Therefore, $\forall I > i, X_I = X_i$.
	 - $X$ noetherian $\Rightarrow$ $X$ satisfies a.c.c. on open sets
	  Let $X_0\subseteq X_1\subseteq\cdots$ be an arbitrary chain of open subsets of $X$. Then $(X\backslash X_1)\subseteq (X\backslash X_2)\subseteq\cdots$ is a chain of closed sets. By assumption, the chain of closed sets has some set $X\backslash X_i$ such that, $\forall I > i, (X\backslash X_I) = (X\backslash X_i)$. Therefore, $\forall I > i, X_I = X_i$.
	 - Every non-empty family of closed sets of $X$ has a maximal element $\Rightarrow$ every non-empty family of open sets of $X$ has a maximal element
	   Let $Y$ be a family of open sets of $X$. Consider the family of closed sets $\tilde{Y}$ consisting of the complement of each set in $Y$ with $X$. By assumption, there is some minimal element $\tilde{Y_i}$. Therefore, the corresponding set $Y_i$ is a maximal element of $Y$.
	 - Every non-empty family of open sets of $X$ has a maximal element $\Rightarrow$ Every non-empty family of closed sets of $X$ has a maximal element
	   Let $Y$ be a family of closed sets of $X$. Consider the family of open sets $\tilde{Y}$ consisting of the complement of each set in $Y$ with $X$. By assumption, there is some maximal element $\tilde{Y_i}$. Therefore, the corresponding set $Y_i$ is a minimal element of $Y$.

**** 1.7b
	 Show that $X$ noetherian $\Rightarrow$ (quasi-)compact

	 Let $\{U\}_\alpha$ be an open cover of $X$ indexed by some set $\alpha$. Using the axiom of choice, construct choice functions $f_1, f_2\cdots$ such that $\forall i\in\mathbb{N}, f_i(\{U\}_\alpha)\backslash(\cup_{j < i} f_j(\{U\}_\alpha))\ne\emptyset$. Now construct a series of closed sets $X\supseteq (X\backslash f_1(\{U\}_\alpha)\supseteq (X\backslash (f_1(\{U\}_\alpha)\cup f_2(\{U\}_\alpha)))\supseteq\cdots$. Because $X$ is noetherian, we know that this eventually terminates after some number of iterations $n$. However, the way that we've constructed our choice function, this means that we're no longer able to find an open cover that has elements distinct from those covered by our previous choices of open sets. However, because $\{U\}_\alpha$ is an open cover, this can only happen once we've covered the whole space. Therefore our open sets $\{f_i(\{U\}_\alpha)\}_{i=1}^{n}$ is an open cover.

	 I wonder if there's a more elegant solution that doesn't necessarily rely on the axiom of choice.

**** 1.7c
	 $X$ noetherian $\Rightarrow$ any subset of $X$ is noetherian with the induced topology

	 Let $S$ be any subset of $X$ and $C_1 = S_1\supseteq S_2\supseteq\cdots$ be a chain of closed subsets in $S$. Because any closed subset in $S$ is the intersection of a closed subset of $X$ and $S$, we have $C_1 = X_1\cap S\supseteq X_2\cap S\cdots$ for some closed subsets $X_1, X_2,\cdots \subset X$. Now consider the chain of subsets $C_2 = X_1\supseteq X_1\cap X_2\supseteq\cdots\supseteq\cap_{i = 1}^j X_i\supseteq\cdots$ (which is a chain of closed subsets because the intersection of an arbitrary family of closed subsets is closed). Because $X$ is noetherian, we know that this sequence stabilizes at some index $i$. Now consider the chain $C_3 = S\cap X_1\supseteq S\cap X_1\cap X_2\supseteq\cdots S\cap_{i=1}^j X_i\supseteq\cdots$. We know that that this sequence eventually stabilizes because $C_2$ stabilizes. We now wish to show that this is equivalent to $C_1$. We'll proceed by induction:
	 Base case: In this case, this reduces to showing that the first element of $C_1$ is equal to the first element of $C_3$; in this case, $X_1\cap S = X_1\cap S$.
	 Induction: Now we wish to show that $X_j\cap S = S\cap_{i=1}^j X_i$. $S\cap_{i=1}^j X_1 = (S\cap_{i=1}^{j-1} X_i)\cap X_j = S_{j-1}\cap X_j = S_j$. We get the final equality because $S_{j-1}\subset S$ so $S_{j-1}\cap X_j\subseteq S\cap X_j = S_j$; however, every element of $S_j$ is an element of both $X_j$ and $S_{j-1}$ so $S_j\subseteq S_{j-1}\cap X_j$

**** 1.7d
	 $X$ noetherian and hausdorff $\Rightarrow$ $X$ is a discrete topological space with finitely many points.

	 Let $X$ be a noetherian hausdorff topological space. Let $p_1, q_1$ be two arbitrary points and let $U_1$ be an open set containing $q_1$ and $T_1$ be an open set containing $p_1$ where $U_1\cap T_1 = \emptyset$. Because subspaces of Hausdorff spaces are themselves Hausdorff, we may inductively define $U_n$ be some open set in $X_n = X\backslash\cup_{i=1}^{n-1}U_i$ that contains some element $q_n\in X_n$ that does not intersect with an open neighborhood of some element $p_n\in X_n$. Then we have a chain $X\supseteq X_1\supseteq\cdots$ of closed sets. Because $X$ is noetherian, this stabilizes for some integer $n$. However, by construction, we have that $X_n = \{p_{n+1}\}$ for, if it contained more than one point, we could create some open set $U_{n+1}$ containing one of the points and not the other, continuing the procedure Furthermore, by the definition of a Hausdorff space, we have that $p_{n+1}$ is an open set because $p_{n+1}$ being the sole element remaining means that it is also open, otherwise the Hausdorff condition would be violated. Because we can pick any element to be the last element remaining in the set (i.e., $\forall i, p_n = p_1$), all points are open. Hence $X$ has the discrete topology. Finally, if $X$ were infinite, say $\{x_1,x_2,\cdots\}$, then $\{x_1,x_2,x_3,\cdots\}\supset \{x_2,x_3,\cdots\}\supset \{x_3,x_4\cdots\}\supset\cdots$ would be an infinite sequence of closed sets which never stabilizes. Hence $X$ must be a finite discrete topological space.

**** 1.8
	 By proposition 1.13, $I(H)$ is generated by a single element $f$ and let $I(Y) = \mathfrak{p} = (f_1,\cdots, f_k)$. Now consider their intersection $I(H\cap Y) = (\mathfrak{p}, f) = (\mathfrak{p}, \overline{f})$ where $\overline{f}$ is $f$ that has possibly been simplified by rewriting parts of $f$ in terms of the generators of $\mathfrak{p}$. In general $\overline{f} = \Pi_{i=1}^k g_i$ where $g_i$ are irreducible polynomials of $k[x_1,\cdots, x_n]$ and $k$ is equal to the number of irreducible components of $H\cap Y$. By our assumption that both $H$ and $Y$ are varieties (and not just algebraic sets), we can conclude that both $I(H)$, $I(Y)$, and each of the $I(C_i) = (\mathfrak{p}, g_i)$ (where $C_i$ are the irreducible components of $I\cap H$) are prime.

	 Showing that each $I(C_i)$ has height at least $n-r+1$ is straightforward because, by theorem 1.8A, $I(Y)$ has height $n-r$ so the chain $\mathfrak{p_0}\subset\cdots\mathfrak{p_{n-r}} = I(Y)\subset I(C_i)$ has height $n-r+1$. Now we want to show that the height of each $I(C_i)$ is exactly $n-r+1$. Because we know that $\mathfrak{p_0}\subset\cdots\mathfrak{p_{n-r}} = I(Y)$ is a chain with the maximum length of $n-r$, we must only show that there is no other prime ideal between $I(Y)$ and $I(C_i)$.

	 Suppose there existed some prime $\mathfrak{q}$ such that $I(Y)\subset\mathfrak{q}\subset I(C_i)$. Because $I(Y)\subset\mathfrak{q}$, $\mathfrak{q} = (\mathfrak{p},g)$ for some element $g\in k[x_1,\cdots, x_n]$. Namely, this implies that $g\in (g_i)$ (because if $g$ can not be written as a combination of the $f_i$, then it must be an element of $(g_i)$ if $\mathfrak{q}\subset I(C_i)$), which is principally generated; therefore $g = g_ih$ for some $h\in k[x_1,\cdots,x_n]$. If $h\not\in (g)$, this would contradict that $(g)$, and by extension $\mathfrak{q}$, is prime; therefore $h = gp$ for some $p\in k[x_1,\cdots,x_n]$. So $g = g_igp \Rightarrow 1 = g_i p$ (because $k[x_1,\cdots,x_n]$ is a commutative integral domain and so the cancellation property holds) and, because $g_i\not\in k$ by assumption and $k[x_1,\cdots,x_n]$ has no other units, we arrive at a contradiction and therefore $I(C_i)$ has height exactly $n-r+1$.
	 
** Section 3
*** Misc Questions
   - Why is a function (on an affine variety) defined to be regular at a point if there is some open set $U$ containing $P$ such that $f = \frac{g}{h}$ for some polynomials $g,h \in k[x_1,...,x_n]$ and then a regular function one that is regular at each point (implying that they are, in general quotients) when it turns out that regular functions are defined to be equal to the affine coordinate ring?

	 It's completely the right definition for being local at a point unambiguously and mirrors localizing the coordinate ring at a point. One reason is that it ties together functions that are regular at a point and regular on the whole variety as "the same thing" (subrings of the same "overarching ring").

	 Furthermore, the local ring of a point is geometrically motivated and it makes proofs easier. A crucial part of theorem 3.2 is showing that $A(Y)_{m_p}$ is isomorphic to the ring of regular functions at $p$; making the "algebraic part" (as opposed to the "topological part" that is the open subsets) be a fraction (since they're represented as equivalence classes of a regular function and an open set) makes the proof very simple.
